create table if not exists public.ad_click_events (
  id bigint generated by default as identity primary key,
  visit_id text not null,
  event_type text not null,
  page_path text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),

  constraint ad_click_events_event_type_check
  check (
    event_type in (
      'phone_list_open',
      'phone_click',
      'naver_talk_click',
      'kakao_talk_click',
      'online_inquiry_click',
      'generate_lead'
    )
  )
);

create index if not exists ad_click_events_visit_id_idx
  on public.ad_click_events (visit_id);

create index if not exists ad_click_events_created_at_idx
  on public.ad_click_events (created_at desc);

create index if not exists ad_click_events_event_type_idx
  on public.ad_click_events (event_type);

alter table public.ad_click_events enable row level security;

revoke all privileges on table public.ad_click_events
  from anon, authenticated;

grant select, insert, update, delete
  on table public.ad_click_events
  to service_role;

comment on table public.ad_click_events is
  '유료광고 방문 이후 발생한 전화, 톡톡, 온라인접수 행동을 visit_id 기준으로 연결한다.';
